---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 32
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
      threshold: "B"
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
