language: java
sudo: false
deploy:
  provider: releases
  file: build/libs/xlr-semaphore-plugin-1.0.1.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-semaphore-plugin
  api_key:
    secure:
      secure: mnZQ+yLceBg1DvBdkbU8KrLdfC950ZY74OXUGKdHfG8dm62SB1wTVrfzPekL2YCYnBUOGMgVwuiH/YvQCwWxM3lorm2XZczYzORUIMzhfLdyFyzmscoI5jVBhB5jTnz50sJPilRZEaN6QXkYOaYYVNXunZktbDDdgy7BEZPJMFYOP2au5y4qJnR6P6WRskzczksLxdXuSDPaP+3bUxPF0tL1iLkU5sL+rTswM5ejMPBVIKoOPsBncDodOz0QGhkSj310zJOPHlBtGBQb/8eZDfP6YtwFRtxgMWcAzEuwP7nbWByU7XUQoudldMD67vsJ+MM1eplKjE9xdFafedqa/HInELmAa8OCT3dBb1NesqspGSu4YDrwsMe8GD9+h2asP85lCPZehnIfGEaUTXpiTeLbfK8jmDLuWcuIC8NPMBAP9oZdPYepn/nue5Vz42BAQwrGwplAov/JVfjeLg6mD3Mk9TniaVdjGYKnTLFewCjmxrk8xDVXRNR7oUKa04Tsmwn/DwFL2BXyOx6nONlecv1HJ9Hv2wskP1aCWY2mm6+8ibDqpyJ4IlEiuADTVFRktDwCMA0+WQT2MjFYfZ7BOoIOJPkhwzykvqeKV7omNvvzftbTOmlR3yDVlq7fEBHkT8LEnTDL89TyhB9a7ewmrQEubACbfbMzB/uGGSLvYck=
notifications:
  hipchat:
    rooms:
      secure: OESHJYQfjr/sCFba/PQq0j0XavfpeqJM5WG86v/SG9ls99cgPdBY2/iDv4ZdMMFqQit9STuCofkAL7xLOD6LIkqFLvjnZhhclRHdrAREW49Tx46uOT9kxcAt/MmO9z6sF6c9eoXW67ddvY6t67stZp/9cfy4mffKSyiS2SYe9rOG5/Oqbx3PVMgVir2XnV+6JFamnE6QQEMQaL44EinkZB1oTWvpCOIy6xEexEr4hKLG1B9dek9Wx6moiCzlcFN9xCom7Qy+I9h28aQ8X43Wm2MANkqR94GwTBc28H8fM7m3VfwyPqBUPA8/r5wyjiza9iPP1lf051m7BkVuDsF8/kw9RJ3WN6WzG/of1tPXnocHLg7iBpoGzaXeFU1r8oBQIjVOe8D6c7W2tN3+8UU6XFwWMMlHJUvaESb72EDGYtNoN3skQLppWlcteFsEWAUqOskOJfG8MQnmH7qvVsXWjZIBqvQ0xq0yK8Gb55L/LlO1AiluXjBPxa0MRaFZC4YE0lxCQDQU8whBrTzHRNyT83+orJg62W/4SiFLrubuhd6LZDjTy+1P8IbzWjZWKx+FCzJ2sz2QCKJanL3uZ94epnBqakDDXLcP9CWL6+mvG9XeRfq+1P9ue6cvDrofys+1hRfWs5b/e/N+0deqU16btpXoAzDJFiv0N2j3Ic5af5Q=
